import Head from "next/head";
import Container from "../components/Container";
import SearchInput from "../components/SearchInput";
import SearchResults from "./Home/SearchResults/SearchResults";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GeekTrust Frontend Challenge - Admin UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h2>Admin UI</h2>
          <form>
            <SearchInput
              id="searchInput"
              name="search-input"
              placeholder="Search here..."
            />
          </form>
          <SearchResults data={[]} />
        </Container>
      </main>
    </div>
  );
}
