import useMembers from "@hooks/useMembers";
import SearchContextProvider from "context/SearchContext";
import Head from "next/head";
import SearchListing from "screens/Home/SearchListing";

export default function Home({ list = [] }) {
  return (
    <div>
      <Head>
        <title>GeekTrust Frontend Challenge - Admin UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchContextProvider data={list}>
          <SearchListing />
        </SearchContextProvider>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const list = (await useMembers()) || [];

  return {
    props: {
      list,
    }, // will be passed to the page component as props
  };
}
